![](cost_state.png)

### Fixed-Length Cost to go

In [1]:
import numpy as np
inf = np.inf


cost4transition = np.array([
    [2.,  2., inf, inf, inf],
    [inf, inf,  1., 4., inf],
    [1.,  inf, inf,  1., inf],
    [inf, inf,  1., inf,  1.],
    [inf, inf, inf, inf, inf]
])

# City Index
a, b, c, d, e = 0, 1, 2, 3, 4
goal = d
# Fixed Length
fixed_length = 5

num_city = len(cost4transition[0])
G = np.full((fixed_length, num_city), inf)
G[0, goal] = 0


def backward_value_iteration(k, G, cost4transition):
    for k in range(1, k):
        for u in range(num_city):
            min_cost = inf
            for x in range(num_city):
                if cost4transition[u, x] != inf:
                    cost = cost4transition[u, x] + G[k-1, x]
                    min_cost = min(min_cost, cost)
            G[k, u] = min_cost
    return G

G = backward_value_iteration(fixed_length, G, cost4transition)
G

array([[inf, inf, inf,  0., inf],
       [inf,  4.,  1., inf, inf],
       [ 6.,  2., inf,  2., inf],
       [ 4.,  6.,  3., inf, inf],
       [ 6.,  4.,  5.,  4., inf]])

### Fixed Length Cost to Come

In [2]:
# Define the initial state and the cost matrix
initial_state = a  # Starting at city A
fixed_length = 5  # Fixed number of steps

C = np.full((fixed_length, num_city), np.inf)
C[0, initial_state] = 0  # Initial cost for the starting city is 0


def forward_value_iteration(C, cost4transition, fixed_length):
    for k in range(1, fixed_length):
        for x_k in range(num_city):
            costs_to_come = [C[k-1, u_k_1] + cost4transition[u_k_1, x_k] for u_k_1 in range(num_city)]
            C[k, x_k] = np.min(costs_to_come)
    return C


C = forward_value_iteration(C, cost4transition, fixed_length)
C


array([[ 0., inf, inf, inf, inf],
       [ 2.,  2., inf, inf, inf],
       [ 4.,  4.,  3.,  6., inf],
       [ 4.,  6.,  5.,  4.,  7.],
       [ 6.,  6.,  5.,  6.,  5.]])

### Unfixed-Length Cost to go

In [3]:
def backward_value_iteration_unfixed_corrected(G, cost4transition):
    updated = True
    
    while updated:
        updated = False  
        for u in range(len(G)):
            if u == goal:  
                continue
            
            current_cost = G[u]  # Current cost for city u
            
            for x in range(len(G)):
                if cost4transition[u, x] != np.inf and G[x] != np.inf:
                    new_cost = cost4transition[u, x] + G[x]
                    if new_cost < current_cost:
                        G[u] = new_cost
                        updated = True
    
    return G

G_unfixed_corrected = np.full(num_city, np.inf)
G_unfixed_corrected[goal] = 0


G_unfixed_final = backward_value_iteration_unfixed_corrected(G_unfixed_corrected, cost4transition)
G_unfixed_final


array([ 4.,  2.,  1.,  0., inf])

Unfixed-Length Cost to come

In [4]:
def forward_value_iteration_unfixed(C, cost4transition):
    updated = True  
    
    while updated:
        updated = False
        for current_city in range(num_city):
            for next_city in range(num_city):
                if cost4transition[current_city, next_city] != np.inf:
                    new_cost = C[current_city] + cost4transition[current_city, next_city]
                    if new_cost < C[next_city]:
                        C[next_city] = new_cost
                        updated = True  
                        
    return C

start = b
C = np.full(num_city, np.inf)  
C[start] = 0  


C_unfixed_result = forward_value_iteration_unfixed(C, cost4transition)
C_unfixed_result


array([2., 0., 1., 2., 3.])