In [6]:
import numpy as np

In [7]:
L1 = np.array([[3, 3, 5],
               [1, -1, 7],
               [0, -2, 4]])

L2 = np.array([[4, 3, 5, 1, 2],
               [-1, 0, -2, 0, -1],
               [-4, 1, 4, 3, 5],
               [-3, 0, -1, 0, -2],
               [3, 2, -7, 3, 8]])

print("L1 = ")
print(L1, "\n")

print("L2 = ")
print(L2, "\n")

L1 = 
[[ 3  3  5]
 [ 1 -1  7]
 [ 0 -2  4]] 

L2 = 
[[ 4  3  5  1  2]
 [-1  0 -2  0 -1]
 [-4  1  4  3  5]
 [-3  0 -1  0 -2]
 [ 3  2 -7  3  8]] 



# 1.

In [8]:
def find_saddle_points1(L):
    L_low = np.max(np.min(L, axis=0))
    L_high = np.min(np.max(L, axis=1))

    if L_low != L_high:
        print("No saddle point")
        return None
    
    return np.argwhere(L == L_low)
    

In [9]:
print("Saddle points in L1 :")
for x, y in find_saddle_points1(L1):
    print(f"- ({x}, {y})")
print("Saddle points in L2 :")
for x, y in find_saddle_points1(L2):
    print(f"- ({x}, {y})")

Saddle points in L1 :
- (2, 2)
Saddle points in L2 :
- (1, 1)
- (1, 3)
- (3, 1)
- (3, 3)


# 2. 

In [10]:
def find_saddle_points2(L):
    saddle_points = []
    for i in range(L.shape[0]):
        for j in range(L.shape[1]):
            if L[i, j] == np.max(L[i, :]) and L[i, j] == np.min(L[:, j]):
                saddle_points.append((i, j))
    return saddle_points

In [11]:
print("Saddle points in L1 :")
for x, y in find_saddle_points2(L1):
    print(f"- ({x}, {y})")
print("Saddle points in L2 :")
for x, y in find_saddle_points2(L2):
    print(f"- ({x}, {y})")

Saddle points in L1 :
- (2, 2)
Saddle points in L2 :
- (1, 1)
- (1, 3)
- (3, 1)
- (3, 3)
